alter table  CAESCONT
ADD CONSTRAINT CONTRATO_CAESCONT
FOREIGN KEY (CODCONTRATO)
REFERENCES CONTRATO(CODCONTRATO);

alter table  CAESCONT
ADD CONSTRAINT ESTACONTA_CAESCONT
FOREIGN KEY (CODESTACONTA)
REFERENCES ESTACONT(CODESTACONT);

alter table  CAESCONT
ADD CONSTRAINT ESTACONTN_CAESCONT
FOREIGN KEY (CODESTACONTN)
REFERENCES ESTACONT(CODESTACONT);

alter table  CAESCONT
ADD CONSTRAINT CACAESCO_CAESCONT
FOREIGN KEY (CODCACAESCO)
REFERENCES CACAESCO(CODCACAESCO);

/*****************************/


alter table  CAESCUAD
ADD CONSTRAINT CUADCONT_CAESCUAD
FOREIGN KEY (CODCUADCONT)
REFERENCES CUADCONT(CODCUADCONT);

alter table  CAESCUAD
ADD CONSTRAINT ESTACUADA_CAESCUAD
FOREIGN KEY (CODESTACUADA)
REFERENCES ESTACUAD(CODESTACUAD);

alter table  CAESCUAD
ADD CONSTRAINT ESTACUADN_CAESCUAD
FOREIGN KEY (CODESTACUADN)
REFERENCES ESTACUAD(CODESTACUAD);

alter table  CAESCUAD
ADD CONSTRAINT CACAESCU_CAESCUAD
FOREIGN KEY (CODCACAESCU)
REFERENCES CACAESCU(CODCACAESCU);

/*****************************/


alter table  CAESORIN
ADD CONSTRAINT ORDEINSP_CAESORIN
FOREIGN KEY (CODORDEINSP)
REFERENCES ORDEINSP(CODORDEINSP);

alter table  CAESORIN
ADD CONSTRAINT ESTAORINA_CAESORIN
FOREIGN KEY (CODESTAORINA)
REFERENCES ESTAORIN(CODESTAORIN);

alter table  CAESORIN
ADD CONSTRAINT ESTAORINN_CAESORIN
FOREIGN KEY (CODESTAORINN)
REFERENCES ESTAORIN(CODESTAORIN);

alter table  CAESORIN
ADD CONSTRAINT CACAORIN_CAESORIN
FOREIGN KEY (CODCACAORIN)
REFERENCES CACAORIN(CODCACAORIN);


/***********************/

alter table  CAESORTR
ADD CONSTRAINT ORDETRAB_CAESORTR
FOREIGN KEY (CODORDETRAB)
REFERENCES ORDETRAB(CODORDETRAB);

alter table  CAESORTR
ADD CONSTRAINT ESTAORTRA_CAESORTR
FOREIGN KEY (CODESTAORTRA)
REFERENCES ESTAORTR(CODESTAORTR);

alter table  CAESORTR
ADD CONSTRAINT ESTAORTRN_CAESORTR
FOREIGN KEY (CODESTAORTRN)
REFERENCES ESTAORTR(CODESTAORTR);

alter table  CAESORTR
ADD CONSTRAINT CACAESOT_CAESORTR
FOREIGN KEY (CODCACAESOT)
REFERENCES CACAESOT(CODCACAESOT);

/************************/


alter table  CAESPOLI
ADD CONSTRAINT CONTRATO_CAESPOLI
FOREIGN KEY (CODCONTRATO)
REFERENCES CONTRATO(CODCONTRATO);

alter table  CAESPOLI
ADD CONSTRAINT ESTAPOLIA_CAESPOLI
FOREIGN KEY (CODESTAPOLIA)
REFERENCES ESTAPOLI(CODESTAPOLI);

alter table  CAESPOLI
ADD CONSTRAINT ESTAPOLIN_CAESPOLI
FOREIGN KEY (CODESTAPOLIN)
REFERENCES ESTAPOLI(CODESTAPOLI);

alter table  CAESPOLI
ADD CONSTRAINT CACAESPO_CAESPOLI
FOREIGN KEY (CODCACAESPO)
REFERENCES CACAESPO(CODCACAESPO);

/******************/

alter table  CAESPROY
ADD CONSTRAINT PROYECTO_CAESPROY
FOREIGN KEY (CODPROYECTO)
REFERENCES PROYECTO(CODPROYECTO);

alter table  CAESPROY
ADD CONSTRAINT ESTAPROYA_CAESPROY
FOREIGN KEY (CODESTAPROYA)
REFERENCES ESTAPROY(CODESTAPROY);

alter table  CAESPROY
ADD CONSTRAINT ESTAPROYN_CAESPROY
FOREIGN KEY (CODESTAPROYN)
REFERENCES ESTAPROY(CODESTAPROY);

alter table  CAESPROY
ADD CONSTRAINT CACAPROY_CAESPROY
FOREIGN KEY (CODCACAPROY)
REFERENCES CACAPROY(CODCACAPROY);

/************************/

alter table  CARGCUAD
ADD CONSTRAINT CUADCONT_CARGCUAD
FOREIGN KEY (CODCUADCONT)
REFERENCES CUADCONT(CODCUADCONT);

alter table  CARGCUAD
ADD CONSTRAINT CLCACUAD_CARGCUAD
FOREIGN KEY (CODCLCACUAD)
REFERENCES CLCACUAD(CODCLCACUAD);

/***************************/


alter table  CLIENTE
ADD CONSTRAINT ESTACLIE_CLIENTE
FOREIGN KEY (CODESTACLIE)
REFERENCES ESTACLIE(CODESTACLIE);

alter table  CLIENTE
ADD CONSTRAINT TERCEROS_CLIENTE
FOREIGN KEY (CODTERCEROS)
REFERENCES ERP.TERCEROS(CODTERCEROS);

/*********************************/

alter table  CLCACUAD
ADD CONSTRAINT ECUENCONTD_CLCACUAD
FOREIGN KEY (CODCUENCONTD)
REFERENCES ERP.CUENCONT(CODCUENCONT);

alter table  CLCACUAD
ADD CONSTRAINT ECUENCONTC_CLCACUAD
FOREIGN KEY (CODCUENCONTC)
REFERENCES ERP.CUENCONT(CODCUENCONT);

/***********************************/



