alter table  ORDETRAB
ADD CONSTRAINT FASEPROY_ORDETRAB
FOREIGN KEY (CODFASEPROY)
REFERENCES FASEPROY(CODFASEPROY);

alter table  ORDETRAB
ADD CONSTRAINT CUADCONT_ORDETRAB
FOREIGN KEY (CODCUADCONT)
REFERENCES CUADCONT(CODCUADCONT);

alter table  ORDETRAB
ADD CONSTRAINT ESTAORTR_ORDETRAB
FOREIGN KEY (CODESTAORTR)
REFERENCES ESTAORTR(CODESTAORTR);

alter table  ORDETRAB
ADD CONSTRAINT CONTRATO_ORDETRAB
FOREIGN KEY (CODCONTRATO)
REFERENCES CONTRATO(CODCONTRATO);


alter table  ORDETRAB
ADD CONSTRAINT CAUSINCU_ORDETRAB
FOREIGN KEY (CODCAUSINCU)
REFERENCES CAUSINCU(CODCAUSINCU);

alter table  ORDETRAB
ADD CONSTRAINT CAUSCUMPL_ORDETRAB
FOREIGN KEY (CODCAUSCUMPL)
REFERENCES CAUSCUMPL(CODCAUSCUMPL);

alter table  ORDETRAB
ADD CONSTRAINT TIPOTRAB_ORDETRAB
FOREIGN KEY (CODTIPOTRAB)
REFERENCES TIPOTRAB(CODTIPOTRAB);

alter table  ORDETRAB
ADD CONSTRAINT PROYECTO_ORDETRAB
FOREIGN KEY (CODPROYECTO)
REFERENCES PROYECTO(CODPROYECTO);

/*******************/

alter table  OTLIORIN
ADD CONSTRAINT LOTEINSP_OTLIORIN
FOREIGN KEY (CODLOTEINSP)
REFERENCES LOTEINSP(CODLOTEINSP);

alter table  OTLIORIN
ADD CONSTRAINT ORDETRAB_OTLIORIN
FOREIGN KEY (CODORDETRAB)
REFERENCES ORDETRAB(CODORDETRAB);

alter table  OTLIORIN
ADD CONSTRAINT ORDEINSP_OTLIORIN
FOREIGN KEY (CODORDEINSP)
REFERENCES ORDEINSP(CODORDEINSP);

/***************************/


alter table  OTROSI
ADD CONSTRAINT CONTRATO_OTROSI
FOREIGN KEY (CODCONTRATO)
REFERENCES CONTRATO(CODCONTRATO);

/************************/

alter table  POLICONT
ADD CONSTRAINT ESTAPOLI_POLICONT
FOREIGN KEY (CODESTAPOLI)
REFERENCES ESTAPOLI(CODESTAPOLI);

alter table  POLICONT
ADD CONSTRAINT ASEGURADORA_POLICONT
FOREIGN KEY (CODASEGURADORA)
REFERENCES ASEGURADORA(CODASEGURADORA);

/*************************/


alter table  PRESACTI
ADD CONSTRAINT PROYECTO_PRESACTI
FOREIGN KEY (CODPROYECTO)
REFERENCES PROYECTO(CODPROYECTO);

alter table  PRESACTI
ADD CONSTRAINT ACTIVIDAD_PRESACTI
FOREIGN KEY (CODACTIVIDAD)
REFERENCES ACTIVIDAD(CODACTIVIDAD)

/**************************/

alter table  PROYCONT
ADD CONSTRAINT PROYECTO_PROYCONT
FOREIGN KEY (CODPROYECTO)
REFERENCES PROYECTO(CODPROYECTO);

alter table  PROYCONT
ADD CONSTRAINT CONTRATO_PROYCONT
FOREIGN KEY (CODCONTRATO)
REFERENCES CONTRATO(CODCONTRATO);
/**************************/

alter table  PROYECTO
ADD CONSTRAINT CLIENTE_PROYECTO
FOREIGN KEY (CODCLIENTE)
REFERENCES CLIENTE(CODCLIENTE);

alter table  PROYECTO
ADD CONSTRAINT ESTAPROY_PROYECTO
FOREIGN KEY (CODESTAPROY)
REFERENCES ESTAPROY(CODESTAPROY);

alter table  PROYECTO
ADD CONSTRAINT CLASPROY_PROYECTO
FOREIGN KEY (CODCLASPROY)
REFERENCES CLASPROY(CODCLASPROY);
/*************************/


alter table  TIAJCLMF
ADD CONSTRAINT CLMOFICO_TIAJCLMF
FOREIGN KEY (CODCLMOFICO)
REFERENCES CLMOFICO(CODCLMOFICO);

alter table  TIAJCLMF
ADD CONSTRAINT TIPOAJUS_TIAJCLMF
FOREIGN KEY (CODTIPOAJUS)
REFERENCES TIPOAJUS(CODTIPOAJUS);
/*************************/

alter table  TITRCOPR
ADD CONSTRAINT TIPOTRAB_TITRCOPR
FOREIGN KEY (CODTIPOTRAB)
REFERENCES TIPOTRAB(CODTIPOTRAB);

alter table  TITRCOPR
ADD CONSTRAINT PROYECTO_TITRCOPR
FOREIGN KEY (CODPROYECTO)
REFERENCES PROYECTO(CODPROYECTO);

alter table  TITRCOPR
ADD CONSTRAINT CONTRATO_TITRCOPR
FOREIGN KEY (CODCONTRATO)
REFERENCES CONTRATO(CODCONTRATO);

alter table  TITRCOPR
ADD CONSTRAINT FASEPROY_TITRCOPR
FOREIGN KEY (CODFASEPROY)
REFERENCES FASEPROY(CODFASEPROY);

/*******************/

alter table  TITRCUAD
ADD CONSTRAINT TIPOTRAB_TITRCUAD
FOREIGN KEY (CODTIPOTRAB)
REFERENCES TIPOTRAB(CODTIPOTRAB);

alter table  TITRCUAD
ADD CONSTRAINT CUADCONT_TITRCUAD
FOREIGN KEY (CODCUADCONT)
REFERENCES CUADCONT(CODCUADCONT);
/*****************/

alter table  TITRPROY
ADD CONSTRAINT TIPOTRAB_TITRPROY
FOREIGN KEY (CODTIPOTRAB)
REFERENCES TIPOTRAB(CODTIPOTRAB);
/*****************/

alter table  ORTRLOIN
ADD CONSTRAINT ORDETRAB_ORTRLOIN
FOREIGN KEY (CODORDETRAB)
REFERENCES ORDETRAB(CODORDETRAB);

alter table  ORTRLOIN
ADD CONSTRAINT LOTEINSP_ORTRLOIN
FOREIGN KEY (CODLOTEINSP)
REFERENCES LOTEINSP(CODLOTEINSP);
/********************/

alter table  TRABFASE
ADD CONSTRAINT FASEPROY_TRABFASE
FOREIGN KEY (CODFASEPROY)
REFERENCES FASEPROY(CODFASEPROY);

alter table  TRABFASE
ADD CONSTRAINT TITRPROY_TRABFASE
FOREIGN KEY (CODTITRPROY)
REFERENCES TITRPROY(CODTITRPROY);


alter table  TRABFASE
ADD CONSTRAINT CUADCONT_TRABFASE
FOREIGN KEY (CODCUADCONT)
REFERENCES CUADCONT(CODCUADCONT);

/*************************/

alter table  TIPOTRAB
ADD CONSTRAINT PLAN_TIPOTRAB
FOREIGN KEY (CODENT,CODPLAN)
REFERENCES ERP.PLAN(CODENT,CUENTA);

alter table  TIPOTRAB
ADD CONSTRAINT CLMOFICO_TIPOTRAB
FOREIGN KEY (CODCLMOFICO)
REFERENCES CLMOFICO(CODCLMOFICO);

/**************************/

alter table  TIPOAJUS
ADD CONSTRAINT CUENCONT_TIPOAJUS
FOREIGN KEY (CODCUENCONT)
REFERENCES ERP.CUENCONT(CODCUENCONT);

/**************************/