alter table  ACTALIQI
ADD CONSTRAINT CONTRATO_ACTALIQI
FOREIGN KEY (CODCONTRATO)
REFERENCES CONTRATO(CODCONTRATO);

alter table  ACTALIQI
ADD CONSTRAINT CUADCONT_ACTALIQI
FOREIGN KEY (CODCUADCONT)
REFERENCES CUADCONT(CODCUADCONT);

alter table  ACTALIQI
ADD CONSTRAINT ESTAACTA_ACTALIQI
FOREIGN KEY (CODESTAACTA)
REFERENCES ESTAACTA(CODESTAACTA);

/**********************************/

alter table  ACTIORTR
ADD CONSTRAINT ORDETRAB_ACTIORTR
FOREIGN KEY (CODORDETRAB)
REFERENCES ORDETRAB(CODORDETRAB);

alter table  ACTIORTR
ADD CONSTRAINT ACTIVIDAD_ACTIORTR
FOREIGN KEY (CODACTIVIDAD)
REFERENCES ACTIVIDAD(CODACTIVIDAD);

alter table  ACTIORTR
ADD CONSTRAINT ACTALIQI_ACTIORTR
FOREIGN KEY (CODACTALIQI)
REFERENCES ACTALIQI(CODACTALIQI);

alter table  ACTIORTR
ADD CONSTRAINT ACTACORT_ACTIORTR
FOREIGN KEY (CODACTACORT)
REFERENCES ACTACORT(CODACTACORT);

/********************************/


alter table  ACTTPRCO
ADD CONSTRAINT ACTIVIDAD_ACTTPRCO
FOREIGN KEY (CODACTIVIDAD)
REFERENCES ACTIVIDAD(CODACTIVIDAD);

alter table  ACTTPRCO
ADD CONSTRAINT TIPOTRAB_ACTTPRCO
FOREIGN KEY (CODTIPOTRAB)
REFERENCES TIPOTRAB(CODTIPOTRAB);

alter table  ACTTPRCO
ADD CONSTRAINT CONTRATO_ACTTPRCO
FOREIGN KEY (CODCONTRATO)
REFERENCES CONTRATO(CODCONTRATO);

alter table  ACTTPRCO
ADD CONSTRAINT PROYECTO_ACTTPRCO
FOREIGN KEY (CODPROYECTO)
REFERENCES PROYECTO(CODPROYECTO);

/******************************/


alter table  CAESACCO
ADD CONSTRAINT ACTACORT_CAESACCO
FOREIGN KEY (CODACTACORT)
REFERENCES ACTACORT(CODACTACORT);

alter table  CAESACCO
ADD CONSTRAINT ESTAACCOA_CAESACCO
FOREIGN KEY (CODESTAACCOA)
REFERENCES ESTAACCO(CODESTAACCO);

alter table  CAESACCO
ADD CONSTRAINT ESTAACCON_CAESACCO
FOREIGN KEY (CODESTAACCON)
REFERENCES ESTAACCO(CODESTAACCO);

alter table  CAESACCO
ADD CONSTRAINT CACAACCO_CAESACCO
FOREIGN KEY (CODCACAACCO)
REFERENCES CACAACCO(CODCACAACCO);

/********************************/

alter table  CAESACTA
ADD CONSTRAINT ACTALIQI_CAESACTA
FOREIGN KEY (CODACTALIQI)
REFERENCES ACTALIQI(CODACTALIQI);

alter table  CAESACTA
ADD CONSTRAINT ESTAACTAA_CAESACTA
FOREIGN KEY (CODESTAACTAA)
REFERENCES ESTAACTA(CODESTAACTA);

alter table  CAESACTA
ADD CONSTRAINT ESTAACTAN_CAESACTA
FOREIGN KEY (CODESTAACTAN)
REFERENCES ESTAACTA(CODESTAACTA);

alter table  CAESACTA
ADD CONSTRAINT CACAESAC_CAESACTA
FOREIGN KEY (CODCACAESAC)
REFERENCES CACAESAC(CODCACAESAC);

/********************************/

alter table  CAESALQO
ADD CONSTRAINT ALQEQUIO_CAESALQO
FOREIGN KEY (CODALQEQUIO)
REFERENCES ALQEQUIO(CODALQEQUIO);

alter table  CAESALQO
ADD CONSTRAINT ESTAALQOA_CAESALQO
FOREIGN KEY (CODESTAALQOA)
REFERENCES ESTAALQO(CODESTAALQO);

alter table  CAESALQO
ADD CONSTRAINT ESTAALQON_CAESALQO
FOREIGN KEY (CODESTAALQON)
REFERENCES ESTAALQO(CODESTAALQO);


alter table  CAESALQO
ADD CONSTRAINT CACAALQO_CAESALQO
FOREIGN KEY (CODCACAALQO)
REFERENCES CACAALQO(CODCACAALQO);

/*******************************/


alter table  CAESCLIE
ADD CONSTRAINT CLIENTE_CAESCLIE
FOREIGN KEY (CODCLIENTE)
REFERENCES CLIENTE(CODCLIENTE);

alter table  CAESCLIE
ADD CONSTRAINT ESTACLIEA_CAESCLIE
FOREIGN KEY (CODESTACLIEA)
REFERENCES ESTACLIE(CODESTACLIE);

alter table  CAESCLIE
ADD CONSTRAINT ESTACLIEN_CAESCLIE
FOREIGN KEY (CODESTACLIEN)
REFERENCES ESTACLIE(CODESTACLIE);

alter table  CAESCLIE
ADD CONSTRAINT CACACLIE_CAESCLIE
FOREIGN KEY (CODCACACLIE)
REFERENCES CACACLIE(CODCACACLIE);

/***********************************/

alter table  ACTITITR
ADD CONSTRAINT ACTIVIDAD_ACTITITR
FOREIGN KEY (CODACTIVIDAD)
REFERENCES ACTIVIDAD(CODACTIVIDAD);

alter table  ACTITITR
ADD CONSTRAINT TIPOTRAB_ACTITITR
FOREIGN KEY (CODTIPOTRAB)
REFERENCES TIPOTRAB(CODTIPOTRAB);

/************************************/

alter table  ACTIVIDAD
ADD CONSTRAINT UNIDAD_ACTIVIDAD
FOREIGN KEY (CODUND)
REFERENCES ERP.UNIDAD(CODUND);

/**********************************/

alter table  AJUSMOFI
ADD CONSTRAINT MOFICONT_AJUSMOFI
FOREIGN KEY (CODMOFICONT)
REFERENCES MOFICONT(CODMOFICONT);

alter table  AJUSMOFI
ADD CONSTRAINT TIPOAJUS_AJUSMOFI
FOREIGN KEY (CODTIPOAJUS)
REFERENCES TIPOAJUS(CODTIPOAJUS);

/***********************************/


alter table  ACTACORT
ADD CONSTRAINT PROYECTO_ACTACORT
FOREIGN KEY (CODPROYECTO)
REFERENCES PROYECTO(CODPROYECTO);

alter table  ACTACORT
ADD CONSTRAINT CLIENTE_ACTACORT
FOREIGN KEY (CODCLIENTE)
REFERENCES CLIENTE(CODCLIENTE);

alter table  ACTACORT
ADD CONSTRAINT ESTAACCO_ACTACORT
FOREIGN KEY (CODESTAACCO)
REFERENCES ESTAACCO(CODESTAACCO);

alter table  ACTACORT
ADD CONSTRAINT FACTCLIE_ACTACORT
FOREIGN KEY (CODFACTCLIE)
REFERENCES ERP.FACTCLIE(CODFACTCLIE);


/**************ESTO ESTA PENDIENTE*******************/

alter table  ALQEQUIO
ADD CONSTRAINT ARTICULO_ALQEQUIO
FOREIGN KEY (CODART)
REFERENCES ERP.ARTICULO(CODART);

alter table  ALQEQUIO
ADD CONSTRAINT PROYECTO_ALQEQUIO
FOREIGN KEY (CODPROYECTO)
REFERENCES PROYECTO(CODPROYECTO);

alter table  ALQEQUIO
ADD CONSTRAINT ORDESERV_ALQEQUIO
FOREIGN KEY (CODORDESERV)
REFERENCES ORDESERV(CODORDESERV);

alter table  ALQEQUIO
ADD CONSTRAINT ESTAALQO_ALQEQUIO
FOREIGN KEY (CODESTAALQO)
REFERENCES ESTAALQO(CODESTAALQO);

/********************************/


