alter table  FASEPROY
ADD CONSTRAINT FASEPROY_FASEPROY
FOREIGN KEY (CODFASEPROYA)
REFERENCES FASEPROY(CODFASEPROY);

alter table  FASEPROY
ADD CONSTRAINT PROYECTO_FASEPROY
FOREIGN KEY (CODPROYECTO)
REFERENCES PROYECTO(CODPROYECTO);

/*********************/

alter table  NOMICUAD
ADD CONSTRAINT CUADCONT_NOMICUAD
FOREIGN KEY (CODCUADCONT)
REFERENCES CUADCONT(CODCUADCONT);

/*************************/

alter table  ORDEINSP
ADD CONSTRAINT CUADCONT_ORDEINSP
FOREIGN KEY (CODCUADCONT)
REFERENCES CUADCONT(CODCUADCONT);
/***************************/

alter table  ORDEREVI
ADD CONSTRAINT CUADCONT_ORDEREVI
FOREIGN KEY (CODCUADCONT)
REFERENCES CUADCONT(CODCUADCONT);

alter table  ORDEREVI
ADD CONSTRAINT ORDETRAB_ORDEREVI
FOREIGN KEY (CODORDETRAB)
REFERENCES ORDETRAB(CODORDETRAB);

/***********************/


alter table  LOTEINSP
ADD CONSTRAINT CUADCONT_LOTEINSP
FOREIGN KEY (CODCUADCONT)
REFERENCES CUADCONT(CODCUADCONT);

alter table  LOTEINSP
ADD CONSTRAINT TIPOTRAB_LOTEINSP
FOREIGN KEY (CODTIPOTRAB)
REFERENCES TIPOTRAB(CODTIPOTRAB);
/************************/

alter table  MOFICONT
ADD CONSTRAINT CLMOFICO_MOFICONT
FOREIGN KEY (CODCLMOFICO)
REFERENCES CLMOFICO(CODCLMOFICO);

alter table  MOFICONT
ADD CONSTRAINT CONTRATO_MOFICONT
FOREIGN KEY (CODCONTRATO)
REFERENCES CONTRATO(CODCONTRATO);

alter table  MOFICONT
ADD CONSTRAINT CUADCONT_MOFICONT
FOREIGN KEY (CODCUADCONT)
REFERENCES CUADCONT(CODCUADCONT);

alter table  MOFICONT
ADD CONSTRAINT ACTALIQI_MOFICONT
FOREIGN KEY (CODACTALIQI)
REFERENCES ACTALIQI(CODACTALIQI);

/**************************/


alter table  ITACTITR
ADD CONSTRAINT ARTICULO_ITACTITR
FOREIGN KEY (CODART)
REFERENCES ERP.ARTICULO(CODART);

alter table  ITACTITR
ADD CONSTRAINT TIPOTRAB_ITACTITR
FOREIGN KEY (CODTIPOTRAB)
REFERENCES TIPOTRAB(CODTIPOTRAB);

alter table  ITACTITR
ADD CONSTRAINT ACTIVIDAD_ITACTITR
FOREIGN KEY (CODACTIVIDAD)
REFERENCES ACTIVIDAD(CODACTIVIDAD);

/**********************************/


alter table  PRESMTPR
ADD CONSTRAINT ARTICULO_PRESMTPR
FOREIGN KEY (CODENT,CODART)
REFERENCES ERP.ARTICULO(CODENT,CODART);

alter table  PRESMTPR
ADD CONSTRAINT PROYECTO_PRESMTPR
FOREIGN KEY (CODPROYECTO)
REFERENCES PROYECTO(CODPROYECTO);



/*****************************/

alter table  ITEMTITR
ADD CONSTRAINT ARTICULO_ITEMTITR
FOREIGN KEY (CODENT)
REFERENCES ERP.EMPRESA(CODENT);





