alter table  CONTRATO
ADD CONSTRAINT ESTACONT_CONTRATO
FOREIGN KEY (CODESTACONT)
REFERENCES ESTACONT(CODESTACONT);

alter table  CONTRATO
ADD CONSTRAINT CUADCONT_CONTRATO
FOREIGN KEY (CODCUADCONT)
REFERENCES CUADCONT(CODCUADCONT);

/****************/


alter table  CUADCONT
ADD CONSTRAINT TERCEROS_CONTRATO
FOREIGN KEY (CODTERCEROS)
REFERENCES ERP.TERCEROS(CODTERCEROS);

alter table  CUADCONT
ADD CONSTRAINT EMPLEADO_CONTRATO
FOREIGN KEY (CODEMP)
REFERENCES timcon.EMPLEADO(CODEMP);

alter table  CUADCONT
ADD CONSTRAINT CLASCUAD_CONTRATO
FOREIGN KEY (CODCLASCUAD)
REFERENCES CLASCUAD(CODCLASCUAD);

alter table  CUADCONT
ADD CONSTRAINT ESTACUAD_CONTRATO
FOREIGN KEY (CODESTACUAD)
REFERENCES ESTACUAD(CODESTACUAD);

/********************/

